export const guests = {
  "y5DUKAbjsT": "Carlos Eduardo, Gladys, Carlos Santiago",
  "dWYsDxq7r6": "Mami, Papi y alexito",
  "wnbVwSwj6G": "Gina y Esteban",
  "4hQTXgug2j": "Ruth Sanabria",
  "YjfSYV36SU": "Edgar González",
  "VYupvh53Df": "Marylu y Elena",
  "Ajz9fvRdXF": "Andrés y Aleja",
  "zgGjuJehGm": "Miguelito",
  "Cv6EXjAq6F": "Fabi",
  "SEdmtdMhAY": "Gonzo y Mel",
  "W9f1h8Yd3s": "Nicolás Castro",
  "jEKfMRBnhE": "Gabo y Nata",
  "Rjc9HF3AAN": "Miguel Rodríguez",
  "VggMYQGaD7": "La gemelis",
  "5pb4fXS8za": "Lucía y Manuel",
  "4ZWjymGaZT": "Majo y Sammy",
  "d4pXrWSjUp": "Oscar Diaz",
  "KNWtcF8KMx": "Jessica y Wilber",
  "nJcSGvjNXy": "Ernesto Martínez",
  "9Mu8jAfxyP": "Juan Ortiz",
  "SKdkc3rU2Z": "Tía Mary y Tío Guillermo",
  "g2BFFrPJEw": "Edwin Martinez",
  "bxHvNj6GJy": "Andrés Olaya",
  "kGEMY3FyEk": "Adiela Rodriguez",
  "9n7s8j5XoP": { nombre: "Chris y Cami", virtual: true, country: "poland" },
  "dag94VD632": { nombre: "Briter", virtual: true, country: "belgium" },
  "abc123doremi": "Los novios",
  "juliana_la_colombiana": "Juliana, la colombiana"
};