export const guests = {
  "y5DUKAbjsT": "Carlos Eduardo, Gladys, Carlos Santiago",
  "dWYsDxq7r6": "Mami, Papi y alexito",
  "wnbVwSwj6G": "Gina y Esteban",
  "4hQTXgug2j": "Ruth Sanabria",
  "YjfSYV36SU": "Edgar González",
  "VYupvh53Df": "Marylu Sanabria",
  "Ajz9fvRdXF": "Andrés y Aleja",
  "zgGjuJehGm": "Miguelito",
  "Cv6EXjAq6F": "Fabi e Isa",
  // "SEdmtdMhAY": "Gonzo y Mel",
  "W9f1h8Yd3s": "Nicolás Castro",
  "jEKfMRBnhE": "Gabo y Nata",
  "Rjc9HF3AAN": "Miguel Rodríguez",
  "VggMYQGaD7": "La gemelis",
  "5pb4fXS8za": "Lucía y Manuel",
  "4ZWjymGaZT": "Majo y Sammy",
  "d4pXrWSjUp": "Oscar Diaz",
  "KNWtcF8KMx": "Jessica y Wilber",
  "nJcSGvjNXy": "Ernesto Martínez",
  "9Mu8jAfxyP": "Juan Ortiz",
  "SKdkc3rU2Z": "Tía Mary y Tío Guillermo",
  "g2BFFrPJEw": "Edwin Martinez",
  "bxHvNj6GJy": "Andrés Olaya",
  "kGEMY3FyEk": "Adiela Rodriguez",
  "9n7s8j5XoP": { nombre: "Chris y Cami", virtual: true, country: "poland" },
  "dag94VD632": { nombre: "Briter", virtual: true, country: "belgium" },
  "o0fnS39Tnov": { nombre: "Vale y Pipe", virtual: true, country: "spain" },
  "abc123doremi": "Los novios",
  "juliana_la_colombiana": "Juliana, la colombiana",
  "8df92w3s2s99": "Daniela Franco",
  "9d8f7g6h5j4k": "Luis -Azeem- Sánchez",
  "oryvnvlei5k3": "Willy -Tuk- Niño",
  "9f7wmto5nyon": "Juan Guevara",
  "reiglthtr456": "Lina Mendoza",
};