export const guests = {
  "y5DUKAbjsT": "Carlos Eduardo, Gladys, Carlos Santiago",
  "dWYsDxq7r6": "Mami, Papi y alexito",
  "wnbVwSwj6G": "Gina y Esteban",
  "4hQTXgug2j": "Ruth",
  "YjfSYV36SU": "Edgar",
  "VYupvh53Df": "Marylu y Elena",
  "Ajz9fvRdXF": "Andres y Aleja",
  "zgGjuJehGm": "Miguelito",
  "Cv6EXjAq6F": "Fabi",
  "SEdmtdMhAY": "Gonzo y Mel",
  "jEKfMRBnhE": "Gabo y Nata",
  "Rjc9HF3AAN": "Migue",
  "VggMYQGaD7": "La gemelis",
  "5pb4fXS8za": "Lucía, Manuel",
  "4ZWjymGaZT": "Majo y Sammy",
  "d4pXrWSjUp": "Oscar Diaz",
  "KNWtcF8KMx": "Jessica y Wilber",
  "nJcSGvjNXy": "Ernesto",
  "9Mu8jAfxyP": "Juan",
  "SKdkc3rU2Z": "Tía Mary y Tío Guillermo",
  "g2BFFrPJEw": "Edwin Martinez",
  "bxHvNj6GJy": "Andres Olaya",
  "kGEMY3FyEk": "Adiela Rodriguez",
};